import type { RoomPreferenceRoomType } from "@/lib/project-preferences/types";
import type { QuestionDef } from "./types";

const AI = true;

const yesNo = [
  { id: "yes", label: "Yes" },
  { id: "no", label: "No" },
] as const;

export const SHARED_QUESTIONS: QuestionDef[] = [
  {
    id: "shared.roomTypeMismatch",
    pack: "shared",
    type: "single",
    title: "The photograph looks like a different room type",
    explanation:
      "You selected one room type, but the saved photo was read as another. Choose which brief to continue with. Architecture in the photo still stays as photographed.",
    options: [
      { id: "keep_selected", label: "Keep my selected room type" },
      { id: "use_detected", label: "Use the type detected from the photo" },
    ],
    visibleIf: [{ observation: "roomTypeMismatch", is: true }],
  },
  {
    id: "shared.style",
    pack: "shared",
    type: "multi",
    title: "What style should this interior have?",
    explanation: "Choose up to three. This is the same style system used for product search — not a second preference.",
    maxSelect: 3,
    allowAiDecide: AI,
    options: [
      { id: "modern", label: "Modern", description: "Clean lines, quiet surfaces" },
      { id: "scandinavian", label: "Scandinavian", description: "Light woods, airy calm" },
      { id: "luxury", label: "Luxury", description: "Richer materials and detail" },
      { id: "minimal", label: "Minimal", description: "Only what the room needs" },
      { id: "rustic", label: "Rustic", description: "Natural texture, warm earth" },
    ],
  },
  {
    id: "shared.budget",
    pack: "shared",
    type: "single",
    title: "What budget level should guide product search?",
    explanation: "This qualitative signal is used when searching real products and when visualizing finish quality.",
    options: [
      { id: "budget-friendly", label: "Budget-friendly", description: "Cost-effective solutions" },
      { id: "balanced", label: "Balanced", description: "Quality and value together" },
      { id: "premium", label: "Premium", description: "Higher-end materials and pieces" },
      { id: "not-sure", label: "Not sure yet", description: "Let the search stay flexible" },
    ],
  },
  {
    id: "shared.priorities",
    pack: "shared",
    type: "multi",
    title: "What should this room get right first?",
    explanation: "Pick what matters most. This guides the design, not a rigid ranking.",
    maxSelect: 3,
    allowAiDecide: AI,
    optional: true,
    options: [
      { id: "appearance", label: "Appearance" },
      { id: "function", label: "Everyday function" },
      { id: "storage", label: "Storage" },
      { id: "durability", label: "Durability" },
      { id: "maintenance", label: "Easy maintenance" },
      { id: "cost", label: "Keeping cost down" },
    ],
  },
  {
    id: "shared.colorsLike",
    pack: "shared",
    type: "colors",
    title: "Which colors should the room lean toward?",
    explanation: "A coherent combination is better than a single forced color. Leave blank to let the existing walls lead.",
    allowAiDecide: AI,
    optional: true,
    maxSelect: 4,
    options: [
      { id: "warm-greige", label: "Warm greige" },
      { id: "soft-ivory", label: "Soft ivory" },
      { id: "warm-white", label: "Warm white" },
      { id: "muted-olive", label: "Muted olive" },
      { id: "soft-blue", label: "Soft blue" },
      { id: "terracotta", label: "Terracotta" },
      { id: "charcoal", label: "Charcoal" },
      { id: "natural-wood", label: "Natural wood tones" },
    ],
  },
  {
    id: "shared.colorsDislike",
    pack: "shared",
    type: "multi",
    title: "Any colors to avoid?",
    optional: true,
    maxSelect: 4,
    options: [
      { id: "cold-grey", label: "Cold grey" },
      { id: "bright-white", label: "Stark bright white" },
      { id: "high-chroma", label: "Loud saturated color" },
      { id: "black-high-gloss", label: "High-gloss black" },
      { id: "gold-chrome-mix", label: "Mixed gold and chrome" },
    ],
  },
  {
    id: "shared.materials",
    pack: "shared",
    type: "multi",
    title: "Which materials feel right?",
    allowAiDecide: AI,
    optional: true,
    maxSelect: 4,
    options: [
      { id: "wood", label: "Wood" },
      { id: "stone", label: "Stone" },
      { id: "textiles", label: "Soft textiles" },
      { id: "matte-metal", label: "Quiet matte metal" },
      { id: "painted-wood", label: "Painted wood" },
      { id: "ceramic", label: "Ceramic / tile" },
    ],
  },
  {
    id: "shared.keep",
    pack: "shared",
    type: "text",
    title: "What must stay in the room?",
    explanation:
      "Name furniture or fixtures that already work. Visible architecture (windows, doors, plumbing) is already preserved from the photograph.",
    allowNotApplicable: true,
    optional: true,
    placeholder: "e.g. keep the existing sofa, radiator, built-in wardrobe",
  },
  {
    id: "shared.exclude",
    pack: "shared",
    type: "text",
    title: "Anything you do not want?",
    allowNotApplicable: true,
    optional: true,
    placeholder: "e.g. no rug, no television, no open shelves",
  },
];

export const LIVING_QUESTIONS: QuestionDef[] = [
  {
    id: "living.tv",
    pack: "living-room",
    type: "yesno",
    title: "Do you want a television in this living room?",
    explanation:
      "An empty construction photo does not mean you do not want a TV. If you are unsure, let the design decide a media wall later.",
    allowAiDecide: AI,
    options: [...yesNo],
    invalidates: ["living.tvSize", "living.mediaFurniture"],
  },
  {
    id: "living.tvSize",
    pack: "living-room",
    type: "single",
    title: "About how large should the television be?",
    explanation: "Approximate preference only. This is not a measured fit.",
    allowAiDecide: AI,
    options: [
      { id: "upto-43", label: "Up to 43″" },
      { id: "43-55", label: "43–55″" },
      { id: "55-65", label: "55–65″" },
      { id: "65-plus", label: "65″ or larger" },
    ],
    visibleIf: [{ answer: "living.tv", equals: "yes" }],
  },
  {
    id: "living.mediaFurniture",
    pack: "living-room",
    type: "single",
    title: "How should the TV sit in the room?",
    allowAiDecide: AI,
    options: [
      { id: "console", label: "Low media console" },
      { id: "wall-mount", label: "Wall-mounted, minimal furniture" },
      { id: "console-storage", label: "Console with closed storage" },
    ],
    visibleIf: [{ answer: "living.tv", equals: "yes" }],
  },
  {
    id: "living.use",
    pack: "living-room",
    type: "multi",
    title: "How will you use the living room?",
    maxSelect: 3,
    allowAiDecide: AI,
    options: [
      { id: "relax", label: "Quiet relaxation" },
      { id: "entertain", label: "Entertaining guests" },
      { id: "everyday", label: "Everyday family use" },
      { id: "read", label: "Reading" },
    ],
  },
  {
    id: "living.seating",
    pack: "living-room",
    type: "multi",
    title: "What seating do you want?",
    explanation: "Primary seating is required for an empty living room. Extra seats stay optional until you choose them.",
    maxSelect: 3,
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "sofa", label: "Sofa" },
      { id: "armchairs", label: "Armchairs" },
      { id: "reading-chair", label: "Reading chair" },
    ],
  },
  {
    id: "living.tables",
    pack: "living-room",
    type: "multi",
    title: "Which tables belong in front of seating?",
    maxSelect: 2,
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "coffee", label: "Coffee table" },
      { id: "side", label: "Side table" },
    ],
  },
  {
    id: "living.storage",
    pack: "living-room",
    type: "single",
    title: "Do you want extra storage or shelving?",
    allowAiDecide: AI,
    allowAlreadyHave: true,
    invalidates: ["living.storageStyle"],
    options: [
      { id: "none", label: "No extra storage" },
      { id: "shelves", label: "Open shelving" },
      { id: "closed", label: "Closed storage" },
      { id: "both", label: "Open and closed" },
    ],
  },
  {
    id: "living.storageStyle",
    pack: "living-room",
    type: "single",
    title: "How should that storage look?",
    allowAiDecide: AI,
    options: [
      { id: "low", label: "Low, along a wall" },
      { id: "tall", label: "Taller cabinet or bookcase" },
      { id: "mixed", label: "A mix of heights" },
    ],
    visibleIfAny: [
      { answer: "living.storage", equals: "shelves" },
      { answer: "living.storage", equals: "closed" },
      { answer: "living.storage", equals: "both" },
    ],
  },
  {
    id: "living.curtains",
    pack: "living-room",
    type: "single",
    title: "How should the windows be dressed?",
    explanation: "Curtains control glare on the glass wall. They are not a television backdrop.",
    allowAiDecide: AI,
    allowAlreadyHave: true,
    allowNotApplicable: true,
    options: [
      { id: "sheer", label: "Sheer" },
      { id: "blackout", label: "Blackout / dim-out" },
      { id: "layered", label: "Layered sheer and blackout" },
      { id: "none", label: "No curtains" },
    ],
    visibleIf: [{ observation: "hasWindows", is: true }],
  },
  {
    id: "living.lighting",
    pack: "living-room",
    type: "multi",
    title: "What lighting layers do you want besides the ceiling?",
    allowAiDecide: AI,
    optional: true,
    maxSelect: 3,
    options: [
      { id: "ambient", label: "Ambient floor or table light" },
      { id: "task", label: "Reading / task light" },
      { id: "decorative", label: "A quiet decorative glow" },
    ],
  },
  {
    id: "living.atmosphere",
    pack: "living-room",
    type: "single",
    title: "Evening atmosphere?",
    allowAiDecide: AI,
    options: [
      { id: "warm-calm", label: "Warm and calm" },
      { id: "bright-social", label: "Brighter for gathering" },
      { id: "flexible", label: "Flexible / dimmable feel" },
    ],
  },
  {
    id: "living.decor",
    pack: "living-room",
    type: "single",
    title: "Should the room include restrained decoration?",
    explanation: "Artwork or a textile can finish a solid wall. This is not a mandatory purchase unless you add it later.",
    allowAiDecide: AI,
    options: [
      { id: "yes", label: "Yes, quietly" },
      { id: "no", label: "Keep it spare" },
    ],
  },
];

export const BEDROOM_QUESTIONS: QuestionDef[] = [
  {
    id: "bedroom.occupants",
    pack: "bedroom",
    type: "single",
    title: "Who is this bedroom for?",
    explanation: "This affects circulation around the bed, not an invented room size.",
    allowAiDecide: AI,
    options: [
      { id: "one", label: "One person" },
      { id: "two", label: "Two people" },
      { id: "child", label: "A child" },
      { id: "guest", label: "Guests" },
    ],
  },
  {
    id: "bedroom.bed",
    pack: "bedroom",
    type: "single",
    title: "What bed do you want?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "king", label: "King" },
      { id: "queen", label: "Queen" },
      { id: "single", label: "Single" },
      { id: "bunk", label: "Bunk" },
      { id: "none", label: "No new bed" },
    ],
  },
  {
    id: "bedroom.wardrobe",
    pack: "bedroom",
    type: "single",
    title: "Do you need wardrobe storage?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    invalidates: ["bedroom.wardrobeType"],
    options: [
      { id: "yes", label: "Yes, new wardrobe" },
      { id: "built-in", label: "Use / keep built-in storage" },
      { id: "no", label: "No extra wardrobe" },
    ],
  },
  {
    id: "bedroom.wardrobeType",
    pack: "bedroom",
    type: "single",
    title: "Freestanding or built-in wardrobe preference?",
    allowAiDecide: AI,
    options: [
      { id: "freestanding", label: "Freestanding" },
      { id: "built-in", label: "Built-in (design proposal, not a shoppable install)" },
    ],
    visibleIf: [{ answer: "bedroom.wardrobe", equals: "yes" }],
  },
  {
    id: "bedroom.bedside",
    pack: "bedroom",
    type: "single",
    title: "Bedside tables?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "two", label: "One on each side" },
      { id: "one", label: "One side only" },
      { id: "none", label: "None" },
    ],
  },
  {
    id: "bedroom.dressing",
    pack: "bedroom",
    type: "yesno",
    title: "Do you want a dressing table?",
    allowAiDecide: AI,
    options: [...yesNo],
  },
  {
    id: "bedroom.reading",
    pack: "bedroom",
    type: "yesno",
    title: "A reading chair in the bedroom?",
    allowAiDecide: AI,
    options: [...yesNo],
  },
  {
    id: "bedroom.curtains",
    pack: "bedroom",
    type: "single",
    title: "Window treatment for sleep?",
    allowAiDecide: AI,
    allowAlreadyHave: true,
    options: [
      { id: "blackout", label: "Blackout" },
      { id: "layered", label: "Layered blackout and sheer" },
      { id: "sheer", label: "Sheer only" },
      { id: "none", label: "No curtains" },
    ],
    visibleIf: [{ observation: "hasWindows", is: true }],
  },
  {
    id: "bedroom.lighting",
    pack: "bedroom",
    type: "multi",
    title: "Lighting besides the ceiling?",
    allowAiDecide: AI,
    maxSelect: 3,
    options: [
      { id: "bedside", label: "Light on both sides of the bed" },
      { id: "ambient", label: "Soft ambient light" },
      { id: "wardrobe", label: "Wardrobe / dressing light" },
    ],
  },
  {
    id: "bedroom.atmosphere",
    pack: "bedroom",
    type: "single",
    title: "Desired atmosphere?",
    allowAiDecide: AI,
    options: [
      { id: "calm-dark", label: "Calm, easy to darken" },
      { id: "airy", label: "Airy and light" },
      { id: "hotel", label: "Quiet hotel-like" },
    ],
  },
  {
    id: "bedroom.extraStorage",
    pack: "bedroom",
    type: "yesno",
    title: "Extra closed storage besides the wardrobe?",
    allowAiDecide: AI,
    options: [...yesNo],
  },
];

export const KITCHEN_QUESTIONS: QuestionDef[] = [
  {
    id: "kitchen.cooking",
    pack: "kitchen",
    type: "single",
    title: "How often is this kitchen used for real cooking?",
    allowAiDecide: AI,
    options: [
      { id: "daily", label: "Daily, seriously" },
      { id: "few", label: "A few times a week" },
      { id: "light", label: "Light / mostly coffee and prep" },
    ],
  },
  {
    id: "kitchen.users",
    pack: "kitchen",
    type: "single",
    title: "How many people cook here regularly?",
    allowAiDecide: AI,
    options: [
      { id: "one", label: "One" },
      { id: "two", label: "Two" },
      { id: "more", label: "More than two" },
    ],
  },
  {
    id: "kitchen.layout",
    pack: "kitchen",
    type: "single",
    title: "Any layout preference?",
    explanation:
      "Visible plumbing, ventilation and electrical points stay where they are photographed. A different layout is an unverified design proposal, not a construction plan.",
    allowAiDecide: AI,
    options: [
      { id: "keep", label: "Keep the photographed work zones" },
      { id: "galley", label: "Galley-like clarity" },
      { id: "l-shape", label: "L-shape if the room allows" },
      { id: "island", label: "Include an island or peninsula if feasible" },
    ],
    invalidates: ["kitchen.island"],
  },
  {
    id: "kitchen.island",
    pack: "kitchen",
    type: "yesno",
    title: "Do you want an island or peninsula?",
    explanation: "Physical fit is unverified without plan dimensions. Plumbing will not be silently moved.",
    allowAiDecide: AI,
    options: [...yesNo],
    visibleIf: [{ answer: "kitchen.layout", equals: "island" }],
  },
  {
    id: "kitchen.appliances",
    pack: "kitchen",
    type: "single",
    title: "Built-in or freestanding appliances?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "built-in", label: "Mostly built-in" },
      { id: "freestanding", label: "Mostly freestanding" },
      { id: "mix", label: "A mix" },
    ],
  },
  {
    id: "kitchen.storage",
    pack: "kitchen",
    type: "single",
    title: "Cabinetry and storage?",
    explanation: "New built-in cabinetry is a design proposal, not an invented shoppable install kit.",
    allowAiDecide: AI,
    options: [
      { id: "closed", label: "Mostly closed cabinets" },
      { id: "open", label: "Some open shelving" },
      { id: "mix", label: "Closed with a few open shelves" },
    ],
  },
  {
    id: "kitchen.surfaces",
    pack: "kitchen",
    type: "multi",
    title: "Countertop and backsplash direction?",
    explanation: "Material preference for the design language. Exact products are only used if later searched and approved.",
    allowAiDecide: AI,
    maxSelect: 3,
    options: [
      { id: "wood", label: "Warm wood" },
      { id: "stone", label: "Stone / composite" },
      { id: "tile", label: "Tile backsplash" },
      { id: "quiet-paint", label: "Quiet painted wall" },
      { id: "durable", label: "Prioritize durability and cleaning" },
    ],
  },
  {
    id: "kitchen.dining",
    pack: "kitchen",
    type: "single",
    title: "Is there a dining spot in this kitchen?",
    allowAiDecide: AI,
    invalidates: ["kitchen.diningSeats"],
    options: [
      { id: "none", label: "No dining here" },
      { id: "table", label: "A dining table" },
      { id: "island-seats", label: "Seating at an island / bar" },
    ],
  },
  {
    id: "kitchen.lighting",
    pack: "kitchen",
    type: "multi",
    title: "Kitchen lighting layers?",
    allowAiDecide: AI,
    maxSelect: 3,
    options: [
      { id: "general", label: "Even general light" },
      { id: "task", label: "Task light over the worktop" },
      { id: "pendant", label: "Pendants over dining or island" },
    ],
  },
];

export const BATHROOM_QUESTIONS: QuestionDef[] = [
  {
    id: "bathroom.wet",
    pack: "bathroom",
    type: "single",
    title: "Shower, bathtub, or both?",
    explanation:
      "Visible plumbing and drainage stay as photographed. Moving a shower or tub is an unverified construction proposal, not a feasible install in this tool.",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    invalidates: ["bathroom.walkIn"],
    options: [
      { id: "shower", label: "Shower" },
      { id: "bathtub", label: "Bathtub" },
      { id: "both", label: "Both" },
    ],
  },
  {
    id: "bathroom.walkIn",
    pack: "bathroom",
    type: "yesno",
    title: "Prefer a walk-in shower if the layout allows?",
    explanation: "Asked only as a preference. Exact clearances are unknown.",
    allowAiDecide: AI,
    options: [...yesNo],
    visibleIfAny: [
      { answer: "bathroom.wet", equals: "shower" },
      { answer: "bathroom.wet", equals: "both" },
    ],
  },
  {
    id: "bathroom.vanity",
    pack: "bathroom",
    type: "single",
    title: "Vanity and washbasin?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "vanity", label: "Vanity with storage" },
      { id: "minimal", label: "Minimal basin, little furniture" },
      { id: "keep", label: "Keep the existing basin zone" },
    ],
  },
  {
    id: "bathroom.mirrorLight",
    pack: "bathroom",
    type: "yesno",
    title: "Dedicated mirror lighting?",
    allowAiDecide: AI,
    options: [...yesNo],
  },
  {
    id: "bathroom.storage",
    pack: "bathroom",
    type: "multi",
    title: "Bathroom storage?",
    allowAiDecide: AI,
    optional: true,
    maxSelect: 3,
    options: [
      { id: "vanity", label: "Vanity drawers" },
      { id: "tall", label: "Tall cabinet" },
      { id: "towels", label: "Towel storage / rail" },
    ],
  },
  {
    id: "bathroom.tiles",
    pack: "bathroom",
    type: "single",
    title: "Tile and surface direction?",
    explanation: "Design language only unless you later approve an exact tile product.",
    allowAiDecide: AI,
    options: [
      { id: "quiet", label: "Quiet, large-format look" },
      { id: "warm", label: "Warm stone or ceramic" },
      { id: "keep", label: "Keep photographed finishes if they exist" },
    ],
  },
  {
    id: "bathroom.finishes",
    pack: "bathroom",
    type: "single",
    title: "Fixture metal finish?",
    allowAiDecide: AI,
    options: [
      { id: "chrome", label: "Chrome" },
      { id: "matte-black", label: "Matte black" },
      { id: "brushed", label: "Brushed / nickel" },
      { id: "mixed-quiet", label: "Keep it quiet and consistent" },
    ],
  },
  {
    id: "bathroom.lighting",
    pack: "bathroom",
    type: "multi",
    title: "Lighting?",
    allowAiDecide: AI,
    maxSelect: 3,
    options: [
      { id: "general", label: "Even general light" },
      { id: "mirror", label: "Mirror / face light" },
      { id: "soft", label: "Softer evening light" },
    ],
  },
  {
    id: "bathroom.access",
    pack: "bathroom",
    type: "yesno",
    title: "Any accessibility needs we should respect?",
    explanation: "If yes, you can describe them in notes. We will not invent grab bars or clearances.",
    optional: true,
    options: [...yesNo],
  },
];

export const OTHER_QUESTIONS: QuestionDef[] = [
  {
    id: "other.purpose",
    pack: "other",
    type: "single",
    title: "What will this space be used for?",
    explanation: "This is not a living-room fallback. Choose a purpose, or describe your own.",
    options: [
      { id: "office", label: "Home office" },
      { id: "dining", label: "Dining room" },
      { id: "hallway", label: "Hallway" },
      { id: "child", label: "Children's room" },
      { id: "guest", label: "Guest room" },
      { id: "utility", label: "Utility room" },
      { id: "hobby", label: "Hobby room" },
      { id: "multipurpose", label: "Multipurpose" },
      { id: "custom", label: "Something else" },
    ],
    invalidates: ["other.purposeText", "other.functions", "other.desk", "other.sleep", "other.dining"],
  },
  {
    id: "other.purposeText",
    pack: "other",
    type: "text",
    title: "Describe the use in your own words",
    placeholder: "e.g. piano practice and occasional guest sleep",
    visibleIf: [{ answer: "other.purpose", equals: "custom" }],
  },
  {
    id: "other.functions",
    pack: "other",
    type: "multi",
    title: "Which functions must this room support?",
    maxSelect: 4,
    visibleIfAny: [
      { answer: "other.purpose", equals: "multipurpose" },
      { answer: "other.purpose", equals: "custom" },
    ],
    options: [
      { id: "sleep", label: "Sleeping" },
      { id: "desk", label: "Desk work" },
      { id: "dining", label: "Dining" },
      { id: "storage", label: "Storage" },
      { id: "play", label: "Play / hobby" },
      { id: "guest", label: "Occasional guests" },
    ],
  },
  {
    id: "other.desk",
    pack: "other",
    type: "yesno",
    title: "Do you need a desk and task chair?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [...yesNo],
    visibleIfAny: [
      { customPurposeIn: ["office", "hobby"] },
      { answer: "other.functions", includes: "desk" },
    ],
  },
  {
    id: "other.sleep",
    pack: "other",
    type: "single",
    title: "Sleeping furniture?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [
      { id: "bed", label: "Bed" },
      { id: "sofa-bed", label: "Sofa that can sleep a guest" },
      { id: "none", label: "No sleeping furniture" },
    ],
    visibleIfAny: [
      { customPurposeIn: ["child", "guest"] },
      { answer: "other.functions", includes: "sleep" },
      { answer: "other.functions", includes: "guest" },
    ],
  },
  {
    id: "other.dining",
    pack: "other",
    type: "yesno",
    title: "Dining table and chairs?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [...yesNo],
    visibleIfAny: [
      { customPurposeIn: ["dining"] },
      { answer: "other.functions", includes: "dining" },
    ],
  },
  {
    id: "other.storage",
    pack: "other",
    type: "yesno",
    title: "Dedicated storage furniture?",
    allowAlreadyHave: true,
    allowAiDecide: AI,
    options: [...yesNo],
    visibleIfAny: [
      { customPurposeIn: ["hallway", "utility", "hobby", "office", "child", "guest", "multipurpose", "custom"] },
      { answer: "other.functions", includes: "storage" },
    ],
  },
  {
    id: "other.lighting",
    pack: "other",
    type: "multi",
    title: "Lighting for this use?",
    allowAiDecide: AI,
    maxSelect: 3,
    options: [
      { id: "general", label: "General ceiling light" },
      { id: "task", label: "Task light at the work surface" },
      { id: "ambient", label: "Softer ambient light" },
    ],
  },
  {
    id: "other.curtains",
    pack: "other",
    type: "single",
    title: "Window treatment?",
    allowAiDecide: AI,
    allowAlreadyHave: true,
    allowNotApplicable: true,
    options: [
      { id: "sheer", label: "Sheer" },
      { id: "blackout", label: "Dim-out / blackout" },
      { id: "none", label: "No curtains" },
    ],
    visibleIf: [{ observation: "hasWindows", is: true }],
  },
];

export const SHARED_CLOSING: QuestionDef[] = [
  {
    id: "shared.lightingTemp",
    pack: "shared",
    type: "single",
    title: "Warm or more neutral light?",
    allowAiDecide: AI,
    options: [
      { id: "warm", label: "Warm (about 2700–3000 K)" },
      { id: "neutral", label: "Neutral white" },
      { id: "mixed", label: "Warm general, slightly brighter task" },
    ],
  },
  {
    id: "shared.notes",
    pack: "shared",
    type: "text",
    title: "Anything else the designer should know?",
    optional: true,
    placeholder: "Materials, must-haves, what to avoid…",
  },
];

export function questionsForRoom(roomType: RoomPreferenceRoomType | null): QuestionDef[] {
  const roomQuestions =
    roomType === "living-room"
      ? LIVING_QUESTIONS
      : roomType === "bedroom"
        ? BEDROOM_QUESTIONS
        : roomType === "kitchen"
          ? KITCHEN_QUESTIONS
          : roomType === "bathroom"
            ? BATHROOM_QUESTIONS
            : roomType === "other"
              ? OTHER_QUESTIONS
              : [];
  return [...SHARED_QUESTIONS, ...roomQuestions, ...SHARED_CLOSING];
}
