"use client";

import * as React from "react";
import { motion } from "framer-motion";
import { Container } from "@/components/ui/Container";
import { cn } from "@/lib/utils";

export interface DisclaimerContentProps {
  className?: string;
}

export const DisclaimerContent: React.FC<DisclaimerContentProps> = ({
  className,
}) => {
  return (
    <section
      className={cn("w-full py-20 md:py-32 relative", className)}
    >
      <Container className="px-6 md:px-8 max-w-[960px]">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut", delay: 0.1 }}
          className="max-w-none text-left"
        >
          <div className="pt-[120px] md:pt-[140px] pb-[120px]">
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              This Disclaimer provides important information regarding the use of
              Arhitekt AI and the AI-generated content provided through our
              platform. Please read this document carefully to understand the
              limitations and responsibilities associated with using our service.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              By accessing or using Arhitekt AI, you acknowledge that you have
              read, understood, and agree to be bound by this Disclaimer.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              1. General Information Only
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Arhitekt AI provides conceptual and informational content designed
              to assist users in exploring architectural and renovation
              possibilities.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              All AI-generated previews, estimates, and suggestions are for
              general guidance only. They are not intended to serve as definitive
              plans, final specifications, or guaranteed outcomes.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Information provided through the platform may be incomplete,
              outdated, or inaccurate. Arhitekt AI does not guarantee the
              accuracy, completeness, or timeliness of any content generated by
              our AI systems.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
              Nothing on the platform should be considered guaranteed, final, or
              exhaustive. All content is provided "as is" for informational
              purposes only.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              2. No Professional Advice
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Arhitekt AI is not a licensed architect, structural engineer,
              lawyer, or financial advisor. The service does not provide
              professional architectural, engineering, legal, or construction
              advice.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              The platform does not replace professional architectural,
              engineering, legal, or construction advice. Users must always
              consult qualified professionals before building, renovating, or
              submitting anything for permits.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Any decision you make based on AI-generated output is made at your
              own risk. Arhitekt AI is not responsible for any consequences
              resulting from decisions made based on information provided through
              the platform.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              3. No Construction or Safety Guarantee
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              AI-generated layouts, 3D previews, or material suggestions are not
              construction-ready plans. They are conceptual visualizations and
              estimates only.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              These outputs are not structurally validated and are not intended
              for direct use in real construction work. They do not comply with
              building codes, safety regulations, or local construction standards
              unless explicitly verified by qualified professionals.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              The platform does not guarantee that any design is safe,
              code-compliant, or structurally sound. All designs, layouts, and
              suggestions must be reviewed, validated, and approved by certified
              engineers, architects, or other qualified professionals before being
              used in real-life projects.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
              Users must get all designs checked and approved by certified
              engineers/architects before using them in real-life projects.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              4. Accuracy, Completeness & Availability
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              While we strive to keep the service reliable and up-to-date, there
              is no guarantee of accuracy or completeness of any result provided
              through Arhitekt AI.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              The platform may contain technical errors, omissions, or outdated
              information. AI-generated content is based on algorithms and data
              that may not reflect the most current standards, regulations, or
              best practices.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Access to the service may be interrupted, limited, or discontinued
              at any time without prior notice. We do not warrant that the service
              will be error-free, uninterrupted, or free of defects.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
              Arhitekt AI reserves the right to modify, suspend, or terminate any
              aspect of the platform at its sole discretion.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              5. Limitation of Liability
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              To the maximum extent permitted by applicable law, Arhitekt AI is
              not liable for any damages arising from:
            </p>
            <ul className="list-disc list-inside mb-3 space-y-2 ml-5">
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                use or misuse of AI-generated content
              </li>
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                construction decisions, financial losses, delays, or disputes
              </li>
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                incorrect interpretations of permits, laws, or regulations
              </li>
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                reliance on any information provided through the platform
              </li>
            </ul>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              This limitation of liability applies to all forms of damages,
              including but not limited to direct, indirect, incidental,
              consequential, special, or punitive damages.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
              Any use of the platform is at the user's own risk. By using
              Arhitekt AI, you agree to assume full responsibility for any
              decisions or actions taken based on information provided through the
              service.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              6. External Links & Third-Party Content
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              The platform may contain links to external websites, tools, or
              resources that are not owned or controlled by Arhitekt AI.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Arhitekt AI is not responsible for:
            </p>
            <ul className="list-disc list-inside mb-3 space-y-2 ml-5">
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                content on third-party websites
              </li>
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                accuracy, availability, or policies of external services
              </li>
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                any damages or losses resulting from use of third-party services
              </li>
            </ul>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
              Following external links is at the user's discretion and risk. We
              recommend reviewing the terms of service and privacy policies of any
              third-party websites you visit.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              7. Changes to This Disclaimer
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Arhitekt AI may update this Disclaimer from time to time to reflect
              changes in our services, legal requirements, or business practices.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              Changes are effective when posted on this page. The "Last updated"
              date at the top of this page will reflect the most recent version.
            </p>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
              We encourage users to review this page periodically to stay informed
              about any updates to this Disclaimer. Your continued use of
              Arhitekt AI after changes are posted constitutes acceptance of the
              updated Disclaimer.
            </p>
          </div>

          <div className="mb-9 md:mb-10">
            <h2 className="text-[20px] md:text-[22px] font-semibold text-white mb-3 mt-8">
              8. Contact
            </h2>
            <p className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)] mb-3">
              If you have questions about this Disclaimer, you can contact us at:
            </p>
            <ul className="list-none space-y-2 mb-3">
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                Email:{" "}
                <a
                  href="mailto:legal@arhitekt.ai"
                  className="text-[#00E6CC] hover:text-[#00F5D4] underline transition-colors"
                >
                  legal@arhitekt.ai
                </a>{" "}
                or{" "}
                <a
                  href="mailto:privacy@arhitekt.ai"
                  className="text-[#00E6CC] hover:text-[#00F5D4] underline transition-colors"
                >
                  privacy@arhitekt.ai
                </a>
              </li>
              <li className="text-[15px] md:text-[16px] leading-[1.65] text-[rgba(255,255,255,0.80)]">
                Website:{" "}
                <a
                  href="https://www.arhitekt.ai"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#00E6CC] hover:text-[#00F5D4] underline transition-colors"
                >
                  www.arhitekt.ai
                </a>
              </li>
            </ul>
          </div>
        </motion.div>
      </Container>
    </section>
  );
};

