export const MAX_PRODUCT_DISCOVERY_ITEMS = 10;
export const MAX_ITEM_SPEC_LENGTH = 120;
export const PRODUCT_DISCOVERY_COOLDOWN_SECONDS = 60;
export const PRODUCT_DISCOVERY_GUARD_OPERATION = "product_discovery";
export const MAX_LOCATION_INPUT_LENGTH = 500;
export const MIN_LOCATION_INPUT_LENGTH = 3;
export const DEFAULT_DISCOVERY_RADIUS_KM = 50;
export const MAX_DISCOVERY_RADIUS_KM = 50;
